# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-parismita-github-io'

google-ID: 'UA-112060364-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Academic', path: 'menu', url: 'academic.html'}
- {name: 'Research', path: 'menu', url: 'research.html'}
- {name: 'Projects', path: 'menu', url: 'projects.html'}
- {name: 'Experince', path: 'menu', url: 'experiences.html'}
- {name: 'CV', path: 'menu', url: 'cv.html'}
- {name: 'Blog', path: 'menu', url: 'blog.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/parismita'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/parismita/'}
- {icon: 'envelope', link: 'mailto:das.parismita@gmail.com'}

post_date_prefix: 'Written on'
