# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-parismita-github-io'

google-ID: 'UA-112060364-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Academic', path: 'menu', url: 'academic.html'}
- {name: 'Research', path: 'menu', url: 'research.html'}
- {name: 'Robotics', path: 'menu', url: 'robotics.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/parismita'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/parismita/'}
- {icon: 'envelope', link: 'mailto:das.parismita@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
